set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -ga terminal-features "*:hyperlinks"

# Prefix
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# Splits
unbind %
bind | split-window -h
unbind '"'
bind - split-window -v

# Reload config
unbind r
bind r source-file ~/.tmux.conf

# Resize panes
bind j resize-pane -D 5
bind k resize-pane -U 5
bind l resize-pane -R 5
bind h resize-pane -L 5
bind -r m resize-pane -Z

# Session root to current path
bind M-c attach-session -c "#{pane_current_path}"

# Mouse
set -g mouse on

# Vi mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
bind-key -T copy-mode-vi Enter send-keys -X cancel
unbind -T copy-mode-vi MouseDragEnd1Pane

# Neovim
set -sg escape-time 10
set-option -g focus-events on

# Misc
set-option -g history-limit 100000
set -g set-titles on
set -g set-titles-string "#T"

# Status bar (gruvbox minimal)
set -g status-right ''
set -g status-right-length 0
set -g status-left '[#{session_name}] '
set-option -g status-style "fg=#bdae93,bg=#3c3836"
set-window-option -g window-status-style "fg=#bdae93,bg=default"
set-window-option -g window-status-current-style "fg=#fabd2f,bg=default"
set-option -g pane-border-style "fg=#3c3836"
set-option -g pane-active-border-style "fg=#504945"
set-option -g message-style "fg=#d5c4a1,bg=#3c3836"
set-window-option -g window-status-bell-style "fg=#3c3836,bg=#fb4934"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

# Keep this last
run '~/.tmux/plugins/tpm/tpm'
